- registry.json
A REST client library for Hypermedia APIs.
> Add theseus

- package-overrides/github/photonstorm/phaser@2.2.2.json
- registry.json
> Phaser registry and @2.2.2 override

- registry.json
See https://github.com/cvrebert/mq4-hover-hover-shim and https://www.npmjs.com/package/mq4-hover-hover-shim
> Add mq4-hover-hover-shim to registry

- package-overrides/github/angular-ui/bootstrap-bower@0.12.0.json
- registry.json
I'm not really sure if I have to use `"format": "global"`or not...
> Add bootstrap-bower@0.12.0.json

- package-overrides/github/angular/bower-angular-mocks@1.3.0.json
> fix: angular-mocks-1.3.x

- package-overrides/github/angular/bower-angular-mocks@1.3.0.json
- package-overrides/github/angular/bower-angular-touch@1.3.0.json
- registry.json
> Allow minor angular versions on 1.3

- package-overrides/github/DataTables/TableTools@2.0.0.json
- registry.json
This PR depends on #139 to be completed.
> Add DataTables TableToolst to registry

- package-overrides/github/angular-translate/bower-angular-translate-loader-static-files@2.5.2.json
- package-overrides/github/angular-translate/bower-angular-translate-storage-cookie@2.5.2.json
- package-overrides/github/angular-translate/bower-angular-translate-storage-local@2.5.2.json
- registry.json
* angular-translate-loader-static-files
* angular-translate-storage-cookie
* angular-translate-storage-local
> Added 3 angular-translate plugins

- package-overrides/github/driftyco/ionic-bower@1.0.0-beta.14.json
this should be the last beta build before they release
> add override ionic-bower@1.0.0-beta.14.json

- package-overrides/npm/golden-layout@1.0.6.json
- registry.json
> Register golden-layout npm override.

- package-overrides/github/mgcrea/angular-strap@2.1.6.json
As discussed here: https://github.com/jspm/registry/issues/160
> Add angular-strap override

- package-overrides/github/tymondesigns/angular-locker@1.2.0.json
- registry.json
Neat angular module for session and localStorage manipulation.
> Add angular-locker override and registry

- package-overrides/npm/breeze.js@1.5.4.json
- registry.json
> package override and registry entry for breeze

- package-overrides/github/witoldsz/angular-http-auth@1.0.0.json
- package-overrides/github/witoldsz/angular-http-auth@1.2.0.json
- registry.json
> Add angular-http-auth registry and override

- package-overrides/github/briancherne/jquery-hoverIntent@1.8.1.json
- registry.json
Useful jquery plugin for predicting user's hover intentions.
> jquery-hoverIntent

- registry.json
mq4-hover-hover-shim has been renamed to mq4-hover-shim
> mq4-hover-hover-shim => mq4-hover-shim

- package-overrides/github/chieffancypants/angular-loading-bar@0.6.0.json
- registry.json
Probably best plug-n-play animated loading bar for Angular's $http service.
> Add angular-loading-bar registry and override

- package-overrides/github/ncuillery/angular-breadcrumb@0.3.3.json
- registry.json
Module for automated breadcrumbs generation in Angular apps.
> Add angular-breadcrumb registry and override

- package-overrides/github/brianreavis/sifter.js@0.4.1.json
- registry.json
Dependency for [selectize](https://github.com/brianreavis/selectize.js).
> Add sifter registry and override

- package-overrides/npm/microplugin@0.0.3.json
- registry.json
> Add microplugin registry and override

- package-overrides/github/mgonto/restangular@1.4.0
- registry.json
Working with REST APIs in Angular made easy.
> Add restangular registry and override

- package-overrides/github/AngularAgility/AngularAgility@0.8.21.json
- registry.json
Nifty pack for advanced angular forms, notifications and working with select2.
> Add angular-agility registry and override

- package-overrides/github/brianreavis/sifter.js@0.4.1.json
- package-overrides/npm/microplugin@0.0.3.json
Those don't work correctly without that in browser.
> Add needed global exports for sifter and microplugin

- package-overrides/github/brianreavis/selectize.js@0.12.0.json
- registry.json
Yay, selectize's dependencies complete, finally adding it. ;)
> Add selectize registry and override

- package-overrides/github/select2/select2@3.4.5.json
- package-overrides/github/select2/select2@3.5.2.json
- registry.json
- select2 has now new official github repo select2/select2 (old ivaynberg/select2 is redirected to this)
- previous override did not have dependencies set
Is it OK to modify registry entry like this? If not, let me know.
> New config for select2

- registry.json
Sorry i'm fundling around with git. Is this what we're looking for, just an entry in the registry.json?
> adding baconjs entry in registry

- package-overrides/github/DataTables/Responsive@1.0.4.json
Added https://github.com/DataTables/Responsive
> Add github:DataTables/Responsive to registry

- package-overrides/github/allpro/layout@1.4.3.json
- package-overrides/github/mar10/fancytree@2.8.0.json
- registry.json
added missing jquery-ui dependencies for fancytree and jquery-ui-layout
> added jquery-ui dependency for fancytree

- package-overrides/github/jamesflorentino/nanoscrollerjs@0.8.4.json
Adds jspm support for jamesflorentino/nanoScrollerJS@cfbcdc2.
> Add override for nano scroller

- package-overrides/github/adityasharat/angular-chosen@v1.0.json
- package-overrides/github/harvesthq/chosen@1.0.0.json
added adityasharat/angular-chosen override and a fix for the harvesthq/chosen override
> adityasharat/angular-chosen override and harvesthq/chosen override fix

- package-overrides/github/harvesthq/chosen@1.0.0.json
added chosen.jquery.min.js to list of files so it would get installed
> added chosen.jquery.min.js to list of files so it will get installed

- package-overrides/github/jamesflorentino/nanoScrollerJS@0.8.4.json
Yeeaaahh…. sorry, I know this probably getting old. But everything should be good now!
> Fixed relative path.

- package-overrides/github/brandly/angular-youtube-embed@1.0.0.json
> fix path for min file

- package-overrides/github/andrefarzat/ng-jcrop@1.1.2.json
- registry.json
> added ng-jcrop

- package-overrides/github/driftyco/ionic-bower@1.0.0-rc.0.json
Ionic 1.0.0-rc.0 is out. Here is an override.
> add ionic 1.0.0-rc.0 override

- package-overrides/github/seiyria/angular-bootstrap-slider@0.1.1.json
- package-overrides/github/seiyria/bootstrap-slider@4.5.4.json
- registry.json
bootstrap-slider -> github:seiyria/bootstrap-slider
> added seiyria/bootstrap-slider

- package-overrides/github/fronteed/iCheck@1.0.2.json
- registry.json
> added fronteed/iCheck

- package-overrides/npm/readable-stream@1.0.33.json
As in https://github.com/jspm/nodelibs-stream/issues/1#issuecomment-77842538
> Fix circular import problem for readable stream 1.0.x series

- package-overrides/npm/js-beautify@1.5.5.json
i commited this earlier , this was a mistake , sorry
> this breaks js-beautify

- registry.json
Closes https://github.com/elwayman02/Js.Edgar/issues/19
> Add Js.Edgar to registry

- registry.json
> added angular-resource

- package-overrides/github/obogo/ux-angularjs-datagrid@1.0.0.json
> feat(obogo/ux-angularjs-datagrid): add shim configuration for ux-datagrid

- package-overrides/github/larrytin/bower-vertxbus.json
- registry.json
> feat(vertxbus): add override for vert.x event bus bridge client

- package-overrides/github/larrytin/bower-vertxbus.json
> fix(vertxbus): fix override for vert.x event bus bridge client

- package-overrides/github/uikit/uikit@2.18.0.json
- registry.json
> Added uikit

- registry.json
Adds the aurelia-animator-css registry entry
> Add aurelia-animator-css

- registry.json
Added an entry for [aurelia-validation](github.com/aurelia/validation)
> Added aurelia-validation

- test/index.js
- test/lib/JsonFile.js
- test/lib/PackageOverrideFile.js
> Validate properties

- registry.json
at https://github.com/forresto/system-coffee now
> changed "coffee" repo name

- registry.json
- handlebars-group-by
- handlebars-layouts
> Added handlebars helpers.

- package-overrides/github/timdream/worldcloud2.js@master.json
forgot the override earlier...
ps: i asked them to tag a release , i will submit another PR then for the tagged version (if they tag it)
> override for wordcloud2

- package-overrides/github/dbushell/Pikaday/Pikaday@1.3.1.json
> Pikaday package override.

- package-overrides/github/malihu/malihu-custom-scrollbar-plugin@3.0.8.json
- registry.json
> Added malihu-custom-scrollbar-plugin

- package-overrides/github/FezVrasta/bootstrap-material-design@0.3.0.json
- registry.json
add bootstrap material design with overrides
> add bootstrap material design

- registry.json
Forgot to update this file after creating the correct registry override under github folder.
> Added nsPopover to registry.json

- package-overrides/github/jackmoore/autosize@3.0.2.json
- registry.json
with cjs format, and without jquery dependency
> added new version of jackmoore's autosize

- package-overrides/github/Dogfalo/materialize@0.96.1.json
- registry.json
added https://github.com/Dogfalo/materialize css framework
> added materialize css framework

- package-overrides/github/mhegazy/typescript@v1.5-beta2.json
- registry.json
I'll send a separate PR to update TypeScript registry entries after the official release of 1.5
> initial version of TypeScript 

- package-overrides/github/KABA-CCEAC/angular.CQRS@0.1.4.json
- registry.json
https://github.com/KABA-CCEAC/angular.CQRS
> Add angular.CQRS

- registry.json
@guybedford what do you think? Kind of makes sense IMO given that React is in the registry and a lot of people work on them together.
> Add Immutable and ImmutableJS mappings

- package-overrides/github/kendo-labs/bower-kendo-ui@2015.1.511.json
> not jquery export, 'kendo'

- package-overrides/github/Automattic/socket.io-client@1.3.5.json
- registry.json
fixes https://github.com/jspm/jspm-cli/issues/780
> added an override for socket.io-client

- package-overrides/github/auth0/lock@7.5.4
- package-overrides/github/auth0/lock@7.5.4.json
Copied from https://github.com/volak/registry/blob/master/package-overrides/github/auth0/lock%407.1.1.json, seems to work.
> Adds auth0/lock override.

- package-overrides/github/julianshapiro/velocity@1.1.2.json
> fix velocity

- registry.json
> add reflect-metadata

- registry.json
Repo: https://github.com/SebastianM/angular2-bootstrap
> add angular2-bootstrap project

- registry.json
> Add vdom-virtualize

- registry.json
> registry.json: fixed typo (quint => qunit)

- registry.json
Add plugin-raw from [matthewbauer/plugin-raw](/matthewbauer/plugin-raw) to JSPM registry.
> Add plugin-raw to registry.

- package-overrides/github/tinymce/tinymce-dist@4.1.7.json
- registry.json
I am in doubt on ho this works.
How do I get my override to match more semvers than just the one that I had to hard code into the file name?
Do I need to set anything else in the package override?
> Added TinyMCE and overrides

- package-overrides/github/chieffancypants/angular-loading-bar@0.8.0.json
that said, it doesn't seem to really do anything. i don't see how this works. @guybedford please take a look?
> fix dep for css file

- registry.json
Library Author prefers non extension based key
> Add cytoscape

- registry.json
Added react-dom to jspm registry
> Added react-dom

- package-overrides/github/weluse/hyperagent@0.1.0.json
- registry.json
There is still an outstanding question in #483 on how to get an override to leak a global from a dependency.
> Added hyperagent

- registry.json
I'd like to add aurelia-flux to jspm registry.
Thanks!
> Added aurelia-flux to registry

- registry.json
Thanks for adding aurelia-auth to this registry.
> aurelia-auth

- package-overrides/npm/sass.js@0.9.2.json
See https://github.com/jspm/jspm-cli/issues/906
> Add override to avoid flaky processing of sass.worker.js in npm:sass.js

- registry.json
Thanks for adding aurelia-swagger-client to the registry.
Warm regards
paul.
> added aurelia-swagger-client

- registry.json
> add numeral

- registry.json
https://bevacqua.github.io/dragula/
> add dragula

- package-overrides/github/goldfire/howler.js@2.0.json
* Only includes the core package since it's stable in the 2.0 branch.
* **plugins** package to be added once stable.
Tested with:
```
npm run jspm -- i howler=github:goldfire/howler.js@2.0 -o "{ 'main': 'src/howler.core.js', 'files': [ 'src/howler.core.js' ] }"
```
> howler.js@2.0

- registry.json
Please see dev branch if you're interested in project itself.
https://github.com/Fermium-co/LINQ4ES2015/tree/dev
Thanks
> Added linq4es2015 to jspm registry

- registry.json
[Redux](https://github.com/rackt/redux)
[React-Redux](https://github.com/rackt/react-redux)
@guybedford what do you think?
> Add Redux and React Redux to registry

- package-overrides/github/moment/moment@2.10.3.json
> fixed moment locales

- package-overrides/github/moment/moment@2.10.3.json
I changed the path to ../moment
> changed moment path

- registry.json
Adds registry info for aurelia's internationalization plugin
> Add aurelia-i18n

- package-overrides/github/angular-ui/ui-layout@0.2.1.json
- package-overrides/github/angular-ui/ui-layout@1.1.0.json
- registry.json
This adds the frontend for MBE and the angular-ui-layout package that it depends upon.
> Add mbe-nodes and angular-ui-layout

- registry.json
Updated registry.json to include c3 - a higher level api for interacting w/d3
> Updated registry.json to include c3

- package-overrides/npm/typescript@1.6.2.json
> add overrides for typescript 1.6.2

- package-overrides/github/cloudinary/cloudinary_js@1.0.25.json
- registry.json
Add cloudinary_js to registry and include overrides for dependent files
> feat(registry): add cloudinary to registry

- registry.json
A React-like user interface micro-library.
See http://riotjs.com/.
> Added riot.

- registry.json
This PR adds the mapping for the `knockout-paging` NPM package.
> Add knockout-paging mapping

- package-overrides/npm/angular2@2.0.0-alpha.27.json
> Added package override for Angular2 a44. Fixes #620

- package-overrides/npm/typescript@1.8.0-dev.json
related: https://github.com/jspm/jspm-cli/issues/1101
> add overrides for typescript@1.8.0-dev nightly build

- package-overrides/npm/language-tags@1.0.3.json
Follow-up of discussion in #569
> Override dependencies for npm:language-tags

- registry.json
I would like to add an entry for aurelia-google-analytics package.
> Update registry.json to add aurelia-google-analytics entry

- package-overrides/github/dhg/Skeleton@2.0.4.json
- registry.json
Added Skeleton css framework (https://github.com/dhg/Skeleton) to registry, and a package override.  Please check, as this is my first contribution to the project!
> added skeleton to registry, and skeleton package override

- registry.json
I've added paths-js, a simple and useful library for writing svg paths.
> paths-js added

- registry.json
It was moved to my organization account
> Renamed sass repository url

- registry.json
Repo: https://github.com/SebastianM/angular2-google-maps
> add angular2-google-maps

- registry.json
I would like to register my aurelia plug-in
> Register my plug-in

- registry.json
A complete Aurelia UI Framework for building business applications for the Web.
> Registration for aurelia-ui-framework

- registry.json
Available here: https://github.com/trueadm/t7
> Add t7, a lightweight virtual DOM templating library

- package-overrides/npm/bluebird@3.1.1.json
This addresses #709. I've tested locally with `jspm install -o` approach and it works smashingly.
> Adding package override for bluebird 3.1.1

- package-overrides/npm/foundation-sites@5.5.1.json
- registry.json
zurb Foundation Source changed from bower to latest npm feed
> Changed Source of Foundation

- registry.json
Updated registry.json to map `zepto` to `npm:zepto`
> Add zepto to registry.json

- registry.json
Added [Onsen UI](https://www.npmjs.com/package/onsenui).
> Added OnsenUI to registry.json

- package-overrides/github/kartik-v/bootstrap-fileinput@4.3.0.json
Add canvas-to-blob dependencies
and required missing images files
> Add canvas-to-blob dependencies

- package-overrides/npm/typescript@1.9.0-dev.json
> add support for typescript nightly 1.9.0-dev

- package-overrides/github/HubSpot/tether@1.1.1.json
- package-overrides/github/twbs/bootstrap@4.0.0-alpha.2.json
override for tether@1.1.1 https://github.com/HubSpot/tether
> add tether@1.1.1

- package-overrides/github/zurb/foundation@6.1.2.json
added foundation 6 version 6.1.2 with sass folders
Note: to get foundation javascript to initialize I had to add below to main.ts
```
aurelia.start().then(a => a.setRoot())
.then(a => {
// Initialize framework
$(document).foundation();
});
```
> added foundation 6  v6.1.2

- package-overrides/github/angular-ui/ui-select@0.14.2.json
Add override for latest release of https://github.com/angular-ui/ui-select (0.14.2).  Closes #642
> angular-ui-select@0.14.0

- registry.json
I've created a scss plugin based on mobilexags, however the use case was too different for his to be useful for me. Bare with me before you think its a cheap imitation, there is method to this madness.
The Sass plugin does a great job of cleanly injecting css from scss/sass into your head OR into a bundle (which in turn uses an IIFE to inject it into head). This is great, if you want that behaviour.  However, i didn't.
We're building an Angular2 seed internally (learning excercise / future planning stuff). Angular2's @component decorators allow you to pass 'styles' in as an array of style strings. Via this we are able to leverage it's shadow DOM emulation and management, lovely style encapsulation, with Angular removing stuff for us when that component is killed. 
So [using mobilexags as …
> Adding scss plugin

- package-overrides/github/cruikshj/knockout-select2@1.0.0.json
- registry.json
https://github.com/cruikshj/knockout-select2
> Add knockout-select2

- package-overrides/github/gvas/knockout-jqueryui@2.2.2.json
- registry.json
https://github.com/gvas/knockout-jqueryui
> Add knockout-jqueryui

- package-overrides/github/highcharts/highcharts@4.2.3.json
- registry.json
https://github.com/highcharts/highcharts
> Add highcharts

- package-overrides/npm/angular@1.5.0-rc.2.json
`meta` is only supported with 0.17
> jspm 0.16 compatibility

- package-overrides/github/angular/bower-material@1.0.6.json
Package override for the latest version of angular material.
> Updated Package Override for Angular Material 1.0.6.

- package-overrides/github/sytelus/cryptojs@3.1.2.json
- registry.json
Might be useful over crypto when converting legacy code to JSPM.
> Add override for CryptoJS

- package-overrides/npm/element-resize-detector@1.1.0.json
- registry.json
> Revert "npm:element-resize-detector override"

- registry.json
Added the jspm resgistry token for "aurelia-ej-bridge" and committed in registry.json file
> Added the jspm resgistry token for aurelia-ej-bridge

- package-overrides/npm/angular2@2.0.0-beta.8.json
- package-overrides/npm/reflect-metadata@0.1.3.json
- package-overrides/npm/zone.js@0.5.15.json
Override for https://github.com/jspm/registry/issues/795.
//cc @amcdnl
It would be good to get confirmation from others using Angular if this is all good. @robwormald perhaps you could take a look here or suggest someone who could?
> Angular2 override

- registry.json
Added aurelia-materialize-css to registry.json
> add npm:aurelia-materialize-css to registry

- registry.json
Solves https://github.com/jspm/registry/issues/842
> Resolve aurelia-notification name conflict

- registry.json
> for aurelia-auth use npm instead of github

- registry.json
- https://github.com/fullcalendar/fullcalendar
> Add fullcalendar to registry

- registry.json
Added aurelia-keyboard-plugin to registry
> Added aurelia-keyboard-plugin to registry

- package-overrides/github/kartik-v/bootstrap-fileinput@4.3.0.json
change canvas-to-blob to the right dependency blueimp-canvas-to-blob
> add the right blueimp-canvas-to-blob

- registry.json
Works like plugin-text via translate for embedding or loading svgs
> add github:npbenjohnson/plugin-svg

- package-overrides/npm/@angular/common@2.0.0-rc.1.json
- package-overrides/npm/@angular/compiler@2.0.0-rc.1.json
- package-overrides/npm/@angular/core@2.0.0-rc.1.json
- package-overrides/npm/@angular/http@2.0.0-rc.1.json
- package-overrides/npm/@angular/platform-browser-dynamic@2.0.0-rc.1.json
- package-overrides/npm/@angular/platform-browser@2.0.0-rc.1.json
- package-overrides/npm/@angular/router@2.0.0-rc.1.json
> add @angular overrides

- package-overrides/github/ceolter/ag-grid@4.0.4.json
To match structure:
- dist
- ag-grid.js
- styles
- ag-grid.css
> Move css dependency down a folder

- package-overrides/npm/action-executor@1.0.2.json
Sets the main file, locks format to cjs.
> Added override for ActionExecutor

- registry.json
> Add create-node

- registry.json
Closes https://github.com/One-com/systemjs-plugin-ko-tpl/issues/1
> Add knockout template plugin

- package-overrides/npm/bootstrap@4.0.0-alpha.2.json
My stab at [this](https://github.com/jspm/jspm-cli/issues/1892#issuecomment-225148153). I am not sure whether the shim part is correct because I haven't looked into that yet.
> Add npm:bootstrap@4.0.0-alpha.2 override

- package-overrides/github/photonstorm/phaser@2.2.2.json
Added shim after suggestion by @guybedford regarding issue systemjs/systemjs#1327
> Added shim consistently with phaser typescript definitions

- registry.json
add aurelia-accordion to the registry
> aurelia-accordion

- package-overrides/npm/aws-sdk@2.4.0.json
Use aws-sdk `dist` bundle as a global.
> Add aws-sdk@2.4.0 override.

- package-overrides/npm/notie@3.2.0.json
I think I got this structured correctly. I tested it out using the cli `-o` option and my app ran correctly.
> Add notie 3.2.0 override

- package-overrides/npm/auth0-lock@10.0.0-rc.1.json
This adds overrides for 10.0.0-rc.1
> Added auth0-lock@10.0.0-rc.1

- registry.json
added aurelia-keycloak plugin registry entry
> add aurelia-keycloak

- package-overrides/github/Semantic-Org/Semantic-UI@2.0.4.json
> Overrides Semantic-UI "peerDependencies"

- registry.json
Added the Arva-js app framework to the jspm registry
> Added Arva-js framework to registry

- package-overrides/npm/c3@0.4.11.json
Adds c3/c3.css as a dependency of c3 main file.
> Add overrides for c3

- registry.json
Added registry entry for aurelia-interactjs, plugin to use interact.js with Aurelia.
> registry update, add aurelia-interactjs

- registry.json
Add aurelia-charts and aurelia-charts-d3
> Add aurelia-charts and aurelia-charts-d3

- package-overrides/npm/jquery-dateformat@1.0.3.json
See https://github.com/jspm/registry/issues/990
> Make up for a missing main in jquery-dateformat's package.json

- registry.json
Add Aurelia Bootstrap to registry
> Add Aurelia Bootstrap

- registry.json
> Add aurelia config

- registry.json
A SharePoint 'Script-On-Demand' (SOD) loader plugin for SystemJS.
> SharePoint SOD loader plugin

- package-overrides/npm/socket.io-client@1.7.1.json
Somehwere this changed from the root folder to the dist folder.
> fix: socket.io-client changes to file location

- package-overrides/github/socketio/socket.io-client@1.7.0.json
see https://github.com/socketio/socket.io-client/pull/1025
> socket.io-client update location of main for > 1.7.0

- registry.json
new official less plugin, according to https://github.com/systemjs/plugin-less/issues/10
> new official less plugin

- registry.json
Added [textures.js ](https://riccardoscalco.github.io/textures/) to registry.json
> added textures.js

- registry.json
Added async.js to registry. 
https://github.com/caolan/async
> added async

- package-overrides/npm/waypoints@4.0.1.json
adds an override which points to the minified non-jquery version of [waypoints](https://github.com/imakewebthings/waypoints)
> waypoints override

- registry.json
@aluanhaddad can you merge it?
> add cb-fetch
