package-overrides/github/JimLiu/angular-ui-tree@2.1.5.json
package-overrides/github/angular-ui-tree/angular-ui-tree@2.1.5.json
registry.json

This package stopped working because it was moved to an organization. I thought jspm handled github redirects, but it was getting a 404 finding the js file for angular-ui-tree after `jspm install` was run on the project. Updated the registry to reflect the correct place and added a new package-override. 
Is there any reason to keep package-overrides/github/JimLiu, or should it be removed as well? I don't want to break things for anyone, but I'm not sure it does any good anymore.

angular-ui-tree moved to an organization

---

registry.json

Holding off adding `any-promise-es6` due to https://github.com/jspm/jspm-cli/issues/427

Add any-promise-angular

---

registry.json

Can be added given that https://github.com/jspm/jspm-cli/issues/427 was a false alarm on my part.

Add any-promise-es6

---

package-overrides/github/rstacruz/nprogress@0.1.6.json

This updates the override config based on feedback from @guybedford in the gitter channel. I have tested this and it works correctly with `import * as nprogress from 'nprogress';` I'm also submitting a PR to the nprogress repo to add the override to their package.json file.

feat(nprogress): add updated package override

---

package-overrides/github/henrikjoreteg/Happy.js@v0.8.json
package-overrides/github/jzaefferer/jquery-validation@1.13.1.json
registry.json

added Happy.js
i have one question/comment though.
Happy.js can be used with either jQuery or Zepto
I have added this override without any dependencies so the user can choose to use it with either one.
But the user will have to remember to install either jQuery or Zepto manually.
i tested the override it works fine but is this the best way to handle this situation or should i be doing something else to handle the OR situation ?

added happy -> github:henrikjoreteg/Happy.js

---

package-overrides/github/jzaefferer/jquery-validation@1.13.1.json

jquery-validation works with jquery >=1.4.4

update jquery-validate jquery version

---

registry.json

`jspm install page` points to `npm:page` 
https://www.npmjs.com/package/page

Add page.js

---

package-overrides/github/mrdoob/three.js@r70.json
registry.json

Example of how to use:
import THREE from 'three.js';
import 'three.js/examples/js/renderers/Projector';

Added overrides and endpoint for three.js

---

package-overrides/github/zurb/bower-foundation@5.0.2.json
package-overrides/github/zurb/bower-foundation@5.5.1.json

SCSS files are needed in some Foundation workflows and should not be excluded.

Update Zurb Foundation to 5.5.1

---

package-overrides/github/bpampuch/pdfmake@0.1.15.json
registry.json

Doesn't link `vfs_fonts.js` as, according to [this](https://github.com/bpampuch/pdfmake#getting-started) it's user's choice which font should be used. [Here](https://github.com/bpampuch/pdfmake/issues/33#issuecomment-45792827) is a guide how to apply custom font.

Added pdfmake@0.1.15

---

registry.json

Is it ok if the name does not match the file extension? Ember hbs is not compatible with Handlebars but uses the same file extension (hbs).

Added plugin-ember-hbs

---

package-overrides/github/vitalets/angular-xeditable@0.1.8.json
registry.json

I know the changed override might break stuff. But the angular dep is missing and what's more important, it uses the minified version by default.
Would this still be ok though?

add alias for angular-xeditable, fix override

---

package-overrides/github/zurb/bower-foundation@5.5.1.json

`import Foundation from 'foundation';` now sets the proper foundation export

Fixed export for foundation

---

.gitignore
.travis.yml
package-overrides/npm/golden-layout@1.0.6.json
package.json
test/index.js
test/lib/JsonFile.js
test/lib/OverrideFile.js
test/lib/RegistryFile.js
test/lib/log.js

command tool from file validation: `node test`
`node test --help`
`node test -e` display only errors if they occurred
`node test <package ...>` validate only `registry.json` and overrides from specific package
`node test ace angular react`
by default validates all
Example fail: https://travis-ci.org/2fd/registry/builds/54988938
Example passing: https://travis-ci.org/2fd/registry/builds/54989331

Registry tests jspm/registry#259 + fix golden-layout@1.0.6.json

---

package-overrides/github/formly-js/angular-formly@5.0.3.json
registry.json

This PR adds angular-formly override so it can find its dependencies while going through `jspm` workflow.

Add angular-formly@5.0.3 Override

---

package-overrides/npm/engine.io-client@1.5.1.json

This is to address: https://github.com/jspm/jspm-cli/issues/627
The referenced commit is the top commit in a branch called "add/ssl-support".
However, this fix depends on https://github.com/jspm/jspm-cli/pull/679

Package override for engine.io-client, xmlhttprequest dependency 

---

package-overrides/github/Semantic-Org/Semantic-UI@1.11.8.json
registry.json

As in https://github.com/jspm/registry/issues/306#issuecomment-93691910, I've tested this and it is working fine for me.
@glen-84 the exports are useful so that the import value of semanticUI is jquery itself - `import $ from 'semantic-ui'` which saves some typing. Also I had to make the CSS file loaded relatively.
Feedback welcome before merge.

Add Semantic-UI

---

package-overrides/github/kasperlewau/angular-bind-notifier@0.0.4.json
registry.json

Added dependency shim and endpoint mapping. 
Installed/imported the package with the following (for testing purposes): 
```js 
jspm install angular-bind-notifier=github:kasperlewau/angular-bind-notifier
import 'angular-bind-notifier';
```
I've read through the [package testing](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#testing-configuration) and the [package dependencies](https://github.com/jspm/registry/wiki/Configuring-Packages-for-jspm#package-dependencies) sections but I cannot make much sense out of it, specifically in terms of package dependencies. 
I've tested manual overrides (`-o`) with the given dependency list (in this case, angular) and they appear to not yield a different result, so I'm not 100% that the changes made in …

Add override for kasperlewau/angular-bind-notifier

---

package-overrides/github/kasperlewau/angular-bind-notifier@0.0.4.json

Now points to dist/angular-bind-notifier as intended, correction of  a mistake introduced in #341. *sorry*.
poke @guybedford

Correct the shim path for angular-bind-notifier.

---

package-overrides/github/IdentityModel/oidc-client@0.2.1.json

was missing the `"format": "global"`

fix oidc-client

---

registry.json

socket.io-client succesfull install depends on a release which fixes https://github.com/jspm/jspm-cli/issues/685, but I think we could merge it now, let people who already installed latest master with `npm i git+https://github.com/jspm/jspm-cli.git -g` enjoy easier workflow for isomorphic apps.

added socket.io-client

---

registry.json

shortlist mapping for [kl-watch-once](https://github.com/kasperlewau/kl-watch-once). 
tested locally, no overrides appear to be necessary to get this running - `import 'kl-watch-once'` works just dandy.

Add kl-watch-once shortlist mapping

---

registry.json

The `github/fetch` polyfill is getting a bit more use at the moment. The only problem is you have to `import 'github:github/fetch'` instead of `import fetch from 'github:github/fetch'`, since it edits global scope. I still think it should be added, though, but happy to hear objections.

Adding fetch to registry

---

registry.json

shortlist mapping for [angular-subscribe](https://github.com/kasperlewau/angular-subscribe).
tested locally, no overrides appear to be necessary to get this running - import 'angular-subscribe' works just dandy.

Add angular-subscribe to the registry shortlist

---

package-overrides/github/isteven/angular-omni-bar@1.0.1.json

This PR should add the required overrides for [isteven-angular-omnibar](https://github.com/isteven/angular-omni-bar)

Added package override for isteven omni bar

---

package-overrides/github/zurb/bower-foundation@5.0.2.json
package-overrides/github/zurb/bower-foundation@5.5.1.json

I've noticed Foundation breaks, at least when using a JS component, as jquery is not in the dependencies section. No css included as dependency as I know that topic is a bit controversial...

Fixed missing jquery dependency

---

package-overrides/github/greensock/GreenSock-JS@1.17.0.json
registry.json

Added greensock and changed the main directory.
Reason for changing the main directory is because when requiring the other files in the package one should be able to do so by doing :
```javascript
import TweenLite from "greensock/TweenLite"
import CSSPlugin from "greensock/plugins/CSSPlugin"
```
While it currently is :
```javascript
import TweenLite from "greensock/src/uncompressed/TweenLite"
import CSSPlugin from "greensock/src/uncompressed/plugin/CSSPlugin"
```

added Greensock

---

package-overrides/github/ajaxorg/ace-builds@1.1.6.json

Some modules rely on `ace.require`, which seems to have its own internal locate/fetch algorithm and doesn't match `cjs`'s `require`.  For example, `ace.require('ace/ext/themelist').themesByName` seems to fetch the file `ace/ext-themelist`, and one might think the equivalent `cjs` line would be `require('ace/ext-themelist').themesByName`, but by that method, `themesByName` is `undefined`.  And even after determining the equivalent `cjs` statement, there will likely be at least a dozen or more others like it, so it's easiest to just use the `noconflict` version.

"lib": "src-noconflict"

---

package-overrides/npm/reflect-metadata@0.1.0.json

prevents node dependencies from getting bundled up

add override for reflect-metadata

---

registry.json

jsSHA is a JavaScript implementation of the complete Secure Hash Standard family

jsSHA added

---

registry.json

Request to add p5.js to the registry. This has become one of the more popular libraries for working with canvas and is a port of the very popular java based library Processing.

add p5.js to registry

---

package-overrides/github/Semantic-Org/Semantic-UI@2.0.4.json

Code doesn't change from previous package-override (except semver it targets), Since Semantic UI v2 adds some really good [features + bugfixes](http://semantic-ui.com/introduction/new.html) I think it's worth keeping it up to date !
Manual Install w/options: 
```javascript
jspm install semantic-ui=github:Semantic-Org/Semantic-UI -o "{
'directories': {
'lib': 'dist'
},
'main': 'semantic',
'shim': {
'semantic': {
'deps': [ 'jquery', 'semantic-ui/semantic.css!' ]
}
},
'dependencies': {
'jquery': 'github:components/jquery',
'css': 'github:systemjs/plugin-css'
}
}"
```

add Semantic-UI release V2

---

package-overrides/github/fraywing/textAngular@1.4.2.json
registry.json

Note: textAngular also depends on a sanitization module and I left it up to consumer of this package to additionally load included `textAngular-sanitize` or original `angular-sanitize` or something different. (for more details see: https://github.com/fraywing/textAngular)

Add textAngular registry and override

---

package-overrides/github/jquery/jquery@2.1.0-beta2.json

The current path seems to point towards a non-existing folder?
Seems like a to big an error to go unnoticed, or am I misconfigured back here?

Fix jquery sizzle path

---

package-overrides/github/socketio/socket.io-client@1.3.6.json
registry.json

Socket.io seem to have changed their github org name to socketio. Github redirects requests so install still works with the old name, but the override is not applied, so the library won't actually load.
This change adds the additional override for the new org name, and updates the registry to point to it.

socket.io-client is now in socketio, not Automattic.

---

registry.json

Vibrant.js is a javascript port of the awesome Palette class in the Android support library.

added vibrant.js

---

package-overrides/github/angular-ui/ui-router@0.2.12.json

As you can see in [angular-ui-router.js](https://github.com/angular-ui/ui-router/blob/805e69bae319e922e4d3265b7ef565058aaff850/release/angular-ui-router.js#L10), `module.exports` is being used to define the module name for angular.
Setting the format here allows for the following.
```js
import angular from 'angular';
import uiRouter from 'angular-ui-router'
angular.module('app', [uiRouter]);
```

Add `format` to angular-ui-router

---

package-overrides/github/Dogfalo/materialize@0.97.0.json

The entire materialize repo is nearly 30MB, this change means we only put the relevant parts into `jspm_packages`.

Scope materialize to the dist directory

---

registry.json

I created a minimal SASS plugin to apply SASS styles directly on the current page:
```js
System.import('./style.scss!');
```
I am a newbie in SystemJS / JSPM and I hope I don't oversight something. It would be great if someone could help with the configuration. I only get it running if I add following to my `config.js` to my consumer projects by hand:
```sh
System.config({
map: {
"scss": "jspm:plugin-sass@0.0.1"
}
});
```
It would be awesome when this could be added automatically so that the consumer only have to make a
```sh
$ jspm install sass
```
and after that everything works out of the box. Unfortunately I don't get it :disappointed:

SASS plugin

---

registry.json

See jspm/jspm-cli#1172 for discussion. This let's you install c3 again.
There is currently a bug preventing the npm version to be used from the JSPM CDN: https://github.com/jspm/npm/issues/99 However this doesn't affect local installs as far as I see and is independent of this pull request.

Use npm for c3 library

---

registry.json

This PR adds the mapping for the `knockout-pre-rendered` NPM package.

Add knockout-pre-rendered mapping

---

package-overrides/npm/parse@1.6.5.json

Ignores the modular pieces of the JS SDK, and only pulls in a pre-compiled browser version.

Add Parse JS SDK override to registry

---

registry.json

`moment` changed to use `npm:moment` as discussed in #613 and #616
Package override taken from moment/moment#2577

npm:moment@2.10.6

---

registry.json

Should that work for ionic2 ?. Also I've tried the github:driftyco/ionic2 and is taking the alpha1 version (github:driftyco/ionic2@2.0.0-alpha.1), but the npm one (npm install ionic@alpha) is taking alpha 30, so preferably to take the npm one

Add ionic2

---

package-overrides/npm/googlediff@0.1.0.json

Apparently my fix in #634 exported an object literal and not the expected `diff_match_patch` function. This should fix that.

Fix googlediff@0.1.0.json

---

registry.json

JSPM had probems creating public/jspm_packages/github/capaj/moonridge-client@0.9.1.js file, so I ditched the capital letter

repo renamed

---

package-overrides/github/fraywing/textAngular@1.4.2.json

The `textAngular-sanitize` is a drop-in replacement for `ngSanitize`.
See here for more info: https://github.com/fraywing/textAngular#where-to-get-it

Update registry for textAngular to add deps for "dist/textAngular-sanitize"

---

package-overrides/github/lightbox2/lightbox2@2.8.1.json

Added the overwrite for the jQuery dependency, the missing css and the missing images. This also  fixes https://github.com/jspm/registry/issues/659
Thanks @guybedford for the hint regarding the package overwrite handling!

added package overwrite for lightbox2@2.8.1

---

package-overrides/github/Dogfalo/materialize@0.97.3.json

Fixed package override based on new release structure of materialize (refer to issue #680)

Create materialize@0.97.3.json to fix issue #680

---

package-overrides/npm/redis@2.4.2.json
registry.json

The override is needed to prevent a broken feature detection attempt that prevents loading the library at all while `jspm run`ning in NodeJS.

Redis alias and override

---

package-overrides/github/invertase/angular-toasty@1.0.4.json

The package [angular-toasty](https://github.com/invertase/angular-toasty) depends on angular and I had to shim it to get it loaded.

Add package override for angular-toasty

---

registry.json

With 4.0 coming, I’m moving generated files out of the D3 git repository. They’ll be available in npm (and a dedicated Bower git repository, but npm is preferred).
I tested this with `jspm install npm:d3` and it appeared to succeed?

Repoint d3 at npm.

---

package-overrides/github/jossef/material-design-icons-iconfont@2.0.4.json

Added overrides Material Design icon font library: https://github.com/jossef/material-design-icons-iconfont

Added overrides Material Design icon font 2.0.4

---

package-overrides/github/nnnick/Chart.js@2.0.0-beta2.json

moment is needed as a dependency for chart.js v2 beta in order for it to load properly

Adding Chart.js v2.0.0-beta2 override

---

package-overrides/github/angular-ui/ui-select@0.14.2.json

After removing the `directories.lib` override in https://github.com/jspm/registry/commit/1ad887e48c2d26e41c50b61d26594094ea649e5f, the path for the main shim is incorrect and is not applying the deps overrides

Fix shim path for angular-ui-select

---

package-overrides/npm/coffee-script@1.10.0.json

This PR adds an override for the `npm:coffee-script` package to disable the `child_process` module. With this override `coffee-script` can be required inside a SystemJS environment without it [throwing an error](https://github.com/jspm/nodelibs-child_process/blob/master/child_process.js) because of it requiring `child_process`. 
The only place where `child_process` is required inside CoffeeScript is within `CoffeeScript.register()` (which is used to patch node's module system to understand how to require `.coffee` files) which shouldn't be of any interest for a SystemJS user anyway.
This PR enables the usage of a `npm:coffee-script` dependency inside the [`system-coffee` plugin](https://github.com/forresto/system-coffee).
Refs: https://github.com/forresto/system-coffee/pull/11
Fixes: …

Add coffee-script@1.10.0.json override

---

package-overrides/github/ajaxorg/ace-builds@1.1.6.json

Allows to import language components ahead of time, to include them in bundles:
```
import ace from 'ace';
import 'ace/mode-javascript.js';
import 'ace/theme-twilight.js';
```
It doesn’t solves the issue with workers components however.

Add “deps” to ace editor components

---

registry.json

just the alias; should not break anything.

Add element-resize-detector alias again

---

registry.json

github package no longer works without package overrides because of new build process

Move i18next to npm

---

package-overrides/npm/materialize-css@0.97.5.json

Might be useful for other people that have issues with installing materialize-css with jspm. 
According to this post (https://github.com/Dogfalo/materialize/issues/1208) they won't maintain this in the main package.
Also have a scoped npm package (https://www.npmjs.com/package/@eriklieben/materialize-css), but not sure if that is the best way to install it. Currently it is already ahead of the official release, because I needed bug fixes that are not in the release 0.97.5

add package override for npm:materialize-css

---

package-overrides/npm/esprima@2.7.2.json

It is standalone and packaged as a UMD.
Fixes https://github.com/jspm/registry/issues/839
Reference: https://github.com/jquery/esprima/issues/1486

Esprima does not need the `fs` and `process` shims

---

package-overrides/npm/angular@@2.0.0-beta.10.json
package-overrides/npm/reflect-metadata@0.1.3.json

Here's a correction to the previous override.
This:
* Updates versions for beta.10+
* Updates the dependency on zone.js and reflect-metadata in jspm 0.17 to be automatic for all files of angular (making angular-polyfills.js only necessary in jspm 0.16).
* Fixes up the zone.js override to correctly load Crypto when running in Node, without having to install all of crypto browserify.

Angular override correction

---

package-overrides/npm/typescript@1.8.0.json

as discussed in https://github.com/jspm/jspm-cli/issues/1662

fix(typescript): fix for '_os.platform is not a function' error

---

registry.json

New attempt at a reloader, adds clientside change debouncing, plugin loaded resource change detection, dynamic dependency parent tracking, recovery on import failure, static build for non-jspm users, Instance specific attachment, and hook for defining a custom module storage provider for unload/reload.

systemjs-reloader

---

package-overrides/npm/typescript@1.9.0-dev.json

This fixes the `_os.platform is not a function` exception which occurs when attempting to use the bundle command in jspm@0.17.0-beta. I experimented with local overrides and this did the trick. @frankwallis, @guybedford, does this look right? I was able to reproduce the issue on multiple systems. typescript@1.8.10 works fine with jspm@0.17.0-beta, and typescript@1.9.0-dev works fine when building with jspm@0.16.35.

Fix _os.platform is not a function error

---

registry.json

node module for this package is "protobufjs", "protobuf" relates to different project. Also typings has this as "protobufjs".  
Sorry for the faff on this, it only just occurred to me that name conflict between jspm and npm package names would make targeting commonjs and system all the more harder.

correct protobuf.js alias inline with npm

---

package-overrides/github/Semantic-Org/Semantic-UI@2.0.4.json

Currently, "*" dependency pulls in jQuery 3.x.x, which breaks Semantic UI. This restores the original "^2.1.4" behavior.
closes https://github.com/jspm/jspm-cli/issues/1918

fix(Semantic-UI@2.0.4.json): Maintain jQuery 2.x.x in Semantic UI

---

package-overrides/github/twbs/bootstrap@3.3.6.json

Bootstrap complains if it gets jQuery 3.x as a dep. This will lock it to 2.x

Lock bootstrap 3.3.6 to use jQuery 2.x

---

package-overrides/github/krispo/angular-nvd3@1.0.7.json

The 1.0.2 angular-nvd3 override isn't working for me.  It works once I add the `main` property and add `nvd3` as a shim dependency.

Adding updated angular-nvd3 override

---

registry.json

This is to add [servicestack-client](https://www.npmjs.com/package/servicestack-client) so it's available from `jspm install`.

Add `servicestack-client` to registry

---

package-overrides/npm/mocha@3.0.0.json

Mocha 3 has recently been released:
https://github.com/mochajs/mocha/blob/master/CHANGELOG.md
As the registry uses semver to resolve override, this commit adds
a new file `mocha@3.0.0.json` which is basically just a copy of
`mocha@2.5.3.json`.
Note that I've only tested this is the browser and not in Node.js

Mocha 3 support

---

package-overrides/npm/openlayers@3.17.1.json

Installing openlayers from npm currently fails with `jspm@0.17.0-beta.25` with the following error:
```
err  Error on processPackageConfig
npm dependency format https://github.com/hegemonic/taffydb/tarball/7d100bcee0e997ee4977e273cdce60bd8933050e not supported by jspm.
```
This override removes the `jsdoc` dependency from the openlayers dependencies.

feat(openlayers): add npm:openlayers override

---

registry.json

This package requires to be built and packages to work, otherwise the references from index.js is wrong, therefore the npm version should be used.

Use npm instead of GitHub for Intl.js

---

package-overrides/github/twbs/bootstrap@3.3.7.json

Bootstrap 3.3.7 jQuery requirements:  [Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 4](https://github.com/twbs/bootstrap/blob/0b9c4a4007c44201dce9a6cc1a38407005c26c86/dist/js/bootstrap.js#L15).

Bootstrap 3.3.7 supports jQuery 3

---

package-overrides/github/google/material-design-lite@1.2.0.json

`material-design-lite`'s `main` field is not recognized from github endpoint.

 	add override for material-design-lite

---

package-overrides/npm/debug@2.2.0.json

Babel imports "debug/node" which causes "(SystemJS) Error loading @node/tty. Can only load node core modules in Node" https://github.com/babel/babel/blob/master/packages/babel-core/src/transformation/file/logger.js

Fix import of "babel-core" w/ debug/node override

---

package-overrides/npm/svgo@0.7.1.json

svgo released a new version that still has not fixed https://github.com/svg/svgo/issues/504. Since the dependencies are not statically declared, we need this override. See the [similar override for 0.6.1](https://github.com/jspm/registry/blob/master/package-overrides/npm/svgo%400.6.1.json). This pull request adds three more plugins that have been written that were not part of 0.6.1:
"../../plugins/removeXMLNS"
"../../plugins/removeElementsByAttr"
"../../plugins/addAttributesToSVGElement"

Use same override for svgo@0.7.1 as 0.6.1

---

package-overrides/npm/typescript@2.1.0.json

Add an override for typescript 2.1.0 specifying source-map-support as a dependency to resolve several recent issues.

Add an override for typescript 2.1.0 specifying source-map-support

---

package-overrides/github/angular-ui/angular-ui-router-bower@0.3.2.json

See https://github.com/jspm/jspm-cli/issues/2197.
Version 0.3.2 of ui-router was [published last month](https://github.com/angular-ui/ui-router/releases/tag/0.3.2), and each version of the library has to have a shim/globals configuration since it depends on the angular global

Add override for angular-ui-router@0.3.2

---

package-overrides/npm/debug@2.5.1.json

to resolve https://github.com/jspm/jspm-cli/issues/2204 and https://github.com/visionmedia/debug/issues/394

npm:debug update override to support 2.5.1

---

package-overrides/github/angular-ui/angular-ui-router-bower@0.3.1.json

See https://github.com/jspm/jspm-cli/pull/2200 and https://github.com/jspm/jspm-cli/issues/2197#issuecomment-269520408 for discussion. The `.js` extension should not be included in `shim` configurations.
I have tested this by doing `jspm install angular-ui-router@0.3.1 -o '{"main": "release/angular-ui-router.js", "shim": {"release/angular-ui-router": {"deps": ["angular"]}},"dependencies": {"angular": "*"}}'` locally and verified that it works. Without this change, ui-router@0.3.1 does not work in jspm@0.17

Fix angular-ui-router@0.3.1 override

---

package-overrides/github/openlayers/openlayers@3.11.2.json

The team behind openlayers choose to change the name of the repository, causing problem in our CI. 
The package name should be adapted

feat(openlayers): add openlayers which should replace the ol3 package

---

package-overrides/github/lordfriend/nya-bootstrap-select@2.1.9.json

I push on PR #1001 an error, so the override was only available for the NPM version of the lib.

feat(nya-bootstrap-select): add github version of override

---

package-overrides/npm/leaflet-draw@0.4.1.json

Essential files were missing from `dist/images/**/*`. Now it grabs the whole `dist/` tree.

Fix npm:leaflet-draw missing essential files

---

package-overrides/npm/tslib@1.0.0.json

Currently trying to use ```importHelpers``` option throws an error due to importing named exports from commonjs, see https://github.com/frankwallis/plugin-typescript/issues/199

add override for tslib to use module entry point

---

package-overrides/npm/tslib@1.0.0.json

see https://github.com/Microsoft/tslib/issues/26#issuecomment-284441324
There is an issue with pointing at the ES module file because not everyone is using a transpiler.
I had to add "esModule": true to make it work with SystemJS@0.20, it seems that commonjs module.exports is hidden behind the 'default' property otherwise, which didn't seem correct to me. Shouldn't it be possible to import module.exports directly without using 'default' or setting 'esModule'?

fix back compatibility with jspm 0.16

---

package-overrides/npm/tslib@1.0.0.json

This allows for correct loading of tslib under jspm 0.17/SystemJS 0.20 while preserving compatibility with jspm 0.16/SystemJS 0.19.
See related discussion in #1040, #1041, and https://github.com/Microsoft/tslib/issues/26.
I have tested this under jspm@0.17.41 with SystemJS@0.20.10 and under jspm@0.16.53 with SystemJS@0.19.46.

add esModule marker for compatibility with SystemJS 0.20

---

package-overrides/npm/typescript@rc.json

add typescript@rc

---

.travis.yml

This fixes the CI failures on Travis caused by the use of hoek, a transitive dependency, that requires node >= 4.x.
This updates the node version used by the CI environment to 4.8.5.
Resolves #1064

fix travis ci failures due to incompatibility between dependency and specified node version

---

package-overrides/npm/d3@4.11.0.json

Without this change, installing `d3@4` creates a directory `d3@4.13.0` containing only a single file, `package.json`, with no script file.

Fix files override for d3@4
